export const ALL_QUESTIONS_START   = 'ALL_QUESTIONS_START';
export const ALL_QUESTIONS_SUCCESS = 'ALL_QUESTIONS_SUCCESS';
export const ALL_QUESTIONS_FAIL    = 'ALL_QUESTIONS_FAIL';

export const ALL_USERS_START =   'ALL_USERS_START';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FAIL =    'ALL_USERS_FAIL';

export const CREATE_QUESTION_START = 'CREATE_QUESTION_START';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAIL = 'CREATE_QUESTION-FAIL';


export const SAVE_ANSWER_START = 'SAVE_ANSWER_START';
export const SAVE_ANSWER_SUCCESS = 'SAVE_ANSWER_SUCCESS';
export const SAVE_ANSWER_FAIL = 'SAVE_ANSWER_FAIL';


export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
